appName: enterprise-app

image:
  repository: image-registry.openshift-image-registry.svc:5000/bala12121986-dev/enterprise-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 8080

config:
  indexHtml: |
    Hello from enterprise-app via GitOps!
    Deployed by ArgoCD + Helm.
